# tests/rhosocial/activerecord_test/feature/basic/ddl/test_ddl_clause_expressions.py
"""Tests for the extracted DDL clause expressions.

Covers ``DefaultValueClause`` / ``IdentityClause`` / ``ReferencesClause`` and
their generic formatting, including the backend override seam (SQLite boolean
DEFAULT, identity attributes, referential actions / deferrability).
"""

import pytest

from rhosocial.activerecord.backend.dialect.exceptions import UnsupportedFeatureError
from rhosocial.activerecord.backend.expression import (
    ColumnConstraint,
    ColumnConstraintType,
    ColumnDefinition,
    DefaultValueClause,
    IdentityClause,
    ReferencesClause,
    TableConstraint,
    TableConstraintType,
)
from rhosocial.activerecord.backend.expression.statements import (
    ForeignKeyConstraint,
    ReferentialAction,
)
from rhosocial.activerecord.backend.expression.types import IntegerType
from rhosocial.activerecord.backend.impl.dummy import DummyDialect
from rhosocial.activerecord.backend.impl.sqlite.dialect import SQLiteDialect


@pytest.fixture
def dummy():
    return DummyDialect()


@pytest.fixture
def sqlite():
    return SQLiteDialect((3, 53, 0))


def _column(dialect, *constraints, **kwargs):
    return ColumnDefinition(dialect, "col", IntegerType(dialect), list(constraints), **kwargs)


# ---------------------------------------------------------------------------
# DefaultValueClause
# ---------------------------------------------------------------------------


def test_default_value_clause_scalar(dummy):
    clause = DefaultValueClause(dummy, 42)
    assert dummy.format_default_value_clause(clause) == ("42", ())


def test_default_value_clause_string_is_escaped(dummy):
    clause = DefaultValueClause(dummy, "o'brien")
    sql, params = dummy.format_default_value_clause(clause)
    assert sql == "'o''brien'"
    assert params == ()


def test_default_value_clause_expression(dummy):
    from rhosocial.activerecord.backend.expression import FunctionCall

    clause = DefaultValueClause(dummy, FunctionCall(dummy, "NOW"))
    sql, params = dummy.format_default_value_clause(clause)
    assert sql == "NOW()"
    assert params == ()


def test_default_value_clause_literal_is_inlined(dummy):
    from rhosocial.activerecord.backend.expression import Literal

    clause = DefaultValueClause(dummy, Literal(dummy, 7))
    sql, params = dummy.format_default_value_clause(clause)
    assert sql == "7"
    assert params == ()


def test_default_constraint_accepts_bare_value(dummy):
    constraint = ColumnConstraint(dummy, ColumnConstraintType.DEFAULT, default_value=5)
    sql, _ = dummy.format_default_constraint(constraint)
    assert sql == " DEFAULT 5"


def test_default_constraint_accepts_clause(dummy):
    clause = DefaultValueClause(dummy, "x")
    constraint = ColumnConstraint(dummy, ColumnConstraintType.DEFAULT, default_value=clause)
    sql, _ = dummy.format_default_constraint(constraint)
    assert sql == " DEFAULT 'x'"


def test_default_constraint_requires_value(dummy):
    constraint = ColumnConstraint(dummy, ColumnConstraintType.DEFAULT, default_value=None)
    with pytest.raises(ValueError, match="default value"):
        dummy.format_default_constraint(constraint)


def test_sqlite_boolean_default_is_inlined(sqlite):
    for value, expected in ((True, "1"), (False, "0")):
        clause = DefaultValueClause(sqlite, value)
        assert sqlite.format_default_value_clause(clause) == (expected, ())


def test_sqlite_string_default_still_escaped(sqlite):
    clause = DefaultValueClause(sqlite, "a'b")
    assert sqlite.format_default_value_clause(clause) == ("'a''b'", ())


# ---------------------------------------------------------------------------
# IdentityClause
# ---------------------------------------------------------------------------


def test_identity_clause_default_generation(dummy):
    sql, params = dummy.format_identity_clause(IdentityClause(dummy))
    assert sql == " GENERATED BY DEFAULT AS IDENTITY"
    assert params == ()


def test_identity_clause_always_and_attributes(dummy):
    clause = IdentityClause(dummy, "ALWAYS", start=10, increment=2, minvalue=1, maxvalue=100)
    sql, _ = dummy.format_identity_clause(clause)
    assert sql == (
        " GENERATED ALWAYS AS IDENTITY "
        "(START WITH 10 INCREMENT BY 2 MINVALUE 1 MAXVALUE 100)"
    )


def test_identity_clause_cycle_flags(dummy):
    assert dummy.format_identity_clause(IdentityClause(dummy, cycle=True))[0].endswith("(CYCLE)")
    assert dummy.format_identity_clause(IdentityClause(dummy, cycle=False))[0].endswith("(NO CYCLE)")


def _identity_column(dialect, **kwargs):
    from rhosocial.activerecord.base.ddl.attributes import IdentityAttribute

    col = _column(dialect)
    col.attributes = dialect.select_column_attributes([IdentityAttribute(**kwargs)])
    return col


def test_column_definition_identity_attribute(dummy):
    col = _identity_column(dummy, generation="BY DEFAULT", start=5)
    sql, _ = col.to_sql()
    assert sql == '"col" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 5)'


def test_generic_column_definition_identity_attribute(sqlite):
    from rhosocial.activerecord.backend.dialect.mixins.ddl_column import DDLColumnMixin

    col = _identity_column(sqlite, generation="ALWAYS")
    sql, _ = DDLColumnMixin.format_column_definition(sqlite, col)
    assert sql == '"col" INTEGER GENERATED ALWAYS AS IDENTITY'


def test_generic_column_definition_identity_start_increment(sqlite):
    from rhosocial.activerecord.backend.dialect.mixins.ddl_column import DDLColumnMixin

    col = _identity_column(sqlite, generation="BY DEFAULT", start=2, increment=3)
    sql, _ = DDLColumnMixin.format_column_definition(sqlite, col)
    assert sql == '"col" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 2 INCREMENT BY 3)'


def test_generic_column_definition_constraints_and_generated(sqlite):
    from rhosocial.activerecord.backend.dialect.mixins.ddl_column import DDLColumnMixin
    from rhosocial.activerecord.backend.expression.statements import (
        GeneratedColumnExpression,
        GeneratedColumnType,
    )

    constraint = ColumnConstraint(sqlite, ColumnConstraintType.NOT_NULL)
    generated = GeneratedColumnExpression(sqlite, IntegerType(sqlite), GeneratedColumnType.STORED)
    col = ColumnDefinition(
        sqlite, "col", IntegerType(sqlite), [constraint], generated_expression=generated
    )
    sql, _ = DDLColumnMixin.format_column_definition(sqlite, col)
    assert "NOT NULL" in sql


def test_generic_column_definition_renders_comment_when_supported(sqlite):
    from rhosocial.activerecord.backend.dialect.mixins.ddl_column import DDLColumnMixin

    class CommentDialect(SQLiteDialect):
        def supports_column_comment(self):
            return True

    dialect = CommentDialect((3, 53, 0))
    col = ColumnDefinition(dialect, "col", IntegerType(dialect), comment="hi")
    sql, _ = DDLColumnMixin.format_column_definition(dialect, col)
    assert sql.endswith("COMMENT 'hi'")


def test_generic_column_definition_comment_gate(sqlite):
    from rhosocial.activerecord.backend.dialect.mixins.ddl_column import DDLColumnMixin

    col = ColumnDefinition(sqlite, "col", IntegerType(sqlite), comment="hi")
    with pytest.raises(UnsupportedFeatureError, match="COMMENT"):
        DDLColumnMixin.format_column_definition(sqlite, col)


# ---------------------------------------------------------------------------
# ReferencesClause
# ---------------------------------------------------------------------------


def test_references_clause_minimal(dummy):
    clause = ReferencesClause(dummy, "authors", ["id"])
    assert dummy.format_references_clause(clause) == ('REFERENCES "authors"("id")', ())


def test_references_clause_requires_columns(dummy):
    clause = ReferencesClause(dummy, "authors", [])
    with pytest.raises(ValueError, match="referenced column"):
        dummy.format_references_clause(clause)


def test_references_clause_actions_and_deferrability(dummy):
    clause = ReferencesClause(
        dummy,
        "authors",
        ["id"],
        on_delete=ReferentialAction.CASCADE,
        on_update=ReferentialAction.SET_NULL,
        deferrable=True,
        initially_deferred=True,
    )
    sql, _ = dummy.format_references_clause(clause)
    assert sql == (
        'REFERENCES "authors"("id") ON DELETE CASCADE ON UPDATE SET NULL '
        "DEFERRABLE INITIALLY DEFERRED"
    )


def test_references_clause_not_deferrable(dummy):
    clause = ReferencesClause(dummy, "a", ["id"], deferrable=False)
    assert dummy.format_references_clause(clause)[0].endswith("NOT DEFERRABLE")


def test_references_clause_deferrable_immediate(dummy):
    clause = ReferencesClause(dummy, "a", ["id"], deferrable=True, initially_deferred=False)
    assert dummy.format_references_clause(clause)[0].endswith("DEFERRABLE INITIALLY IMMEDIATE")


def test_references_clause_deferrable_without_initially(dummy):
    clause = ReferencesClause(dummy, "a", ["id"], deferrable=True)
    assert dummy.format_references_clause(clause)[0].endswith("DEFERRABLE")


def test_references_clause_accepts_string_actions(dummy):
    clause = ReferencesClause(dummy, "a", ["id"], on_delete="CASCADE")
    sql, _ = dummy.format_references_clause(clause)
    assert sql.endswith("ON DELETE CASCADE")


def test_references_clause_on_update_gate(dummy):
    class NoOnUpdate(DummyDialect):
        def supports_foreign_key_on_update(self):
            return False

    clause = ReferencesClause(NoOnUpdate(), "a", ["id"], on_update=ReferentialAction.CASCADE)
    with pytest.raises(UnsupportedFeatureError, match="ON UPDATE"):
        NoOnUpdate().format_references_clause(clause)


def test_references_clause_match_gate(dummy):
    class NoMatch(DummyDialect):
        def supports_fk_match(self):
            return False

    clause = ReferencesClause(NoMatch(), "a", ["id"], match_type="FULL")
    with pytest.raises(UnsupportedFeatureError, match="MATCH"):
        NoMatch().format_references_clause(clause)


def test_references_clause_on_delete_gate(dummy):
    class NoOnDelete(DummyDialect):
        def supports_foreign_key_on_delete(self):
            return False

    clause = ReferencesClause(NoOnDelete(), "a", ["id"], on_delete=ReferentialAction.CASCADE)
    with pytest.raises(UnsupportedFeatureError, match="ON DELETE"):
        NoOnDelete().format_references_clause(clause)


def test_column_fk_constraint_delegates_to_references(dummy):
    constraint = ColumnConstraint(
        dummy,
        ColumnConstraintType.FOREIGN_KEY,
        foreign_key_reference=("authors", ["id"]),
        on_delete=ReferentialAction.CASCADE,
    )
    sql, _ = dummy.format_column_fk_constraint(constraint)
    assert sql == ' REFERENCES "authors"("id") ON DELETE CASCADE'


def test_column_fk_constraint_requires_reference(dummy):
    constraint = ColumnConstraint(dummy, ColumnConstraintType.FOREIGN_KEY)
    with pytest.raises(ValueError, match="foreign_key_reference"):
        dummy.format_column_fk_constraint(constraint)


def test_table_fk_constraint_uses_actions(dummy):
    fk = ForeignKeyConstraint(
        dummy,
        columns=["author_id"],
        foreign_key_table="authors",
        foreign_key_columns=["id"],
        on_delete=ReferentialAction.CASCADE,
        on_update=ReferentialAction.RESTRICT,
        match_type="FULL",
    )
    sql, _ = dummy.format_foreign_key_constraint(fk)
    assert sql == (
        'FOREIGN KEY ("author_id") REFERENCES "authors"("id") '
        "MATCH FULL ON DELETE CASCADE ON UPDATE RESTRICT"
    )


def test_table_fk_constraint_without_actions(dummy):
    tc = TableConstraint(
        dummy,
        TableConstraintType.FOREIGN_KEY,
        columns=["author_id"],
        foreign_key_table="authors",
        foreign_key_columns=["id"],
    )
    sql, _ = dummy.format_foreign_key_constraint(tc)
    assert sql == 'FOREIGN KEY ("author_id") REFERENCES "authors"("id")'


def test_table_fk_constraint_requires_columns(dummy):
    tc = TableConstraint(
        dummy,
        TableConstraintType.FOREIGN_KEY,
        foreign_key_table="authors",
        foreign_key_columns=["id"],
    )
    with pytest.raises(ValueError, match="local column"):
        dummy.format_foreign_key_constraint(tc)


def test_table_fk_constraint_requires_referenced_columns(dummy):
    tc = TableConstraint(dummy, TableConstraintType.FOREIGN_KEY, columns=["a"], foreign_key_table="authors")
    with pytest.raises(ValueError, match="foreign key column"):
        dummy.format_foreign_key_constraint(tc)


def test_table_fk_constraint_requires_table(dummy):
    tc = TableConstraint(dummy, TableConstraintType.FOREIGN_KEY, columns=["a"], foreign_key_columns=["id"])
    with pytest.raises(ValueError, match="foreign key table"):
        dummy.format_foreign_key_constraint(tc)
