# tests/rhosocial/activerecord_test/feature/backend/test_identity_capability_conformance.py
"""A dialect's identity / auto-increment declaration and renderer must agree.

Two mechanisms, two nodes, two protocols:

* ``IdentityClause`` / ``IdentityColumnSupport`` -- the SQL-standard
  parameterised ``GENERATED ... AS IDENTITY`` clause;
* ``AutoIncrementClause`` / ``AutoIncrementColumnSupport`` -- the parameterless
  ``AUTO_INCREMENT`` marker.

Both mixins default every probe to ``False`` (fail-closed): a probe answering
``True`` by default would let the formatter emit SQL the server rejects. The
conformance rule is therefore checked in both directions, per dialect:

* probe ``True`` -> the formatter renders the clause;
* probe ``False`` -> the formatter refuses it with ``UnsupportedFeatureError``,
  naming the mechanism or the exact option that was requested -- it never
  silently drops an option, because dropping it changes the statement's
  meaning.

The gate is exercised per option, not once for the whole clause: withdrawing a
single parameter probe must refuse exactly that parameter while the others keep
rendering. The withdrawal is modelled with ``DummyDialect`` subclasses, the
same shape the sequence conformance test uses, so a dialect whose server
refuses one option is represented rather than left unexercised.

``DummyDialect`` declares every probe ``True`` and ``SQLiteDialect`` inherits
the ``False`` defaults, so both branches have a real subject.
"""

import pytest

from rhosocial.activerecord.backend.dialect.exceptions import UnsupportedFeatureError
from rhosocial.activerecord.backend.expression.statements import (
    AutoIncrementClause,
    IdentityClause,
)
from rhosocial.activerecord.backend.impl.dummy.dialect import DummyDialect
from rhosocial.activerecord.backend.impl.sqlite.dialect import SQLiteDialect


#: Every dialect core ships. Each is checked against its own declaration.
CORE_DIALECTS = (DummyDialect, SQLiteDialect)

#: One identity option -> the probe that gates it, the constructor kwargs that
#: request it, the SQL fragment it renders, and the feature name the refusal
#: must carry.
IDENTITY_OPTION_CASES = (
    ("supports_identity_start", {"start": 10}, "START WITH 10", "IDENTITY START"),
    ("supports_identity_increment", {"increment": 5}, "INCREMENT BY 5", "IDENTITY INCREMENT"),
    ("supports_identity_minvalue", {"minvalue": 1}, "MINVALUE 1", "IDENTITY MINVALUE"),
    ("supports_identity_maxvalue", {"maxvalue": 100}, "MAXVALUE 100", "IDENTITY MAXVALUE"),
    ("supports_identity_cycle", {"cycle": True}, "CYCLE", "IDENTITY CYCLE"),
    ("supports_identity_cycle", {"cycle": False}, "NO CYCLE", "IDENTITY CYCLE"),
)

IDENTITY_OPTION_IDS = [
    f"{probe}-{sorted(kwargs)}" for probe, kwargs, _, _ in IDENTITY_OPTION_CASES
]


def _withdrawing_dialect(probe_name: str) -> type:
    """A ``DummyDialect`` that answers one probe ``False``, everything else Dummy's.

    The shape being modelled: a dialect that supports the clause but whose
    server refuses one specific option.
    """
    return type(
        f"DummyWithout_{probe_name}",
        (DummyDialect,),
        {probe_name: lambda self: False},
    )


class TestMechanismDeclarationMatchesImplementation:
    """A ``True`` mechanism probe must render; a ``False`` one must refuse."""

    @pytest.mark.parametrize("dialect_cls", CORE_DIALECTS, ids=lambda c: c.__name__)
    def test_identity_declaration_matches_render(self, dialect_cls):
        dialect = dialect_cls()
        declared = dialect.supports_identity_column()
        try:
            sql = IdentityClause(dialect).to_sql()[0]
        except UnsupportedFeatureError:
            assert declared is False, (
                f"{dialect_cls.__name__} answers supports_identity_column() with "
                f"{declared!r} yet the formatter refused the clause; a declared "
                f"capability needs a renderer."
            )
            return
        assert declared is True, (
            f"{dialect_cls.__name__} answers supports_identity_column() with "
            f"{declared!r} yet rendered {sql!r}; a non-True answer must fail closed."
        )
        assert sql == " GENERATED BY DEFAULT AS IDENTITY"

    @pytest.mark.parametrize("dialect_cls", CORE_DIALECTS, ids=lambda c: c.__name__)
    def test_auto_increment_declaration_matches_render(self, dialect_cls):
        dialect = dialect_cls()
        declared = dialect.supports_auto_increment_column()
        try:
            sql = AutoIncrementClause(dialect).to_sql()[0]
        except UnsupportedFeatureError:
            assert declared is False, (
                f"{dialect_cls.__name__} answers supports_auto_increment_column() "
                f"with {declared!r} yet the formatter refused the marker; a "
                f"declared capability needs a renderer."
            )
            return
        assert declared is True, (
            f"{dialect_cls.__name__} answers supports_auto_increment_column() "
            f"with {declared!r} yet rendered {sql!r}; a non-True answer must fail closed."
        )
        assert sql == " AUTO_INCREMENT"


class TestIdentityOptionGates:
    """Each identity option is gated by its own probe, and refusal names it."""

    @pytest.mark.parametrize(
        "probe_name,kwargs,fragment,feature",
        IDENTITY_OPTION_CASES,
        ids=IDENTITY_OPTION_IDS,
    )
    def test_false_probe_refuses_the_option_by_name(
        self, probe_name, kwargs, fragment, feature
    ):
        """Withdrawing the probe must refuse, naming the option -- never drop it."""
        dialect = _withdrawing_dialect(probe_name)()
        with pytest.raises(UnsupportedFeatureError, match=feature):
            IdentityClause(dialect, **kwargs).to_sql()

    @pytest.mark.parametrize(
        "probe_name,kwargs,fragment,feature",
        IDENTITY_OPTION_CASES,
        ids=IDENTITY_OPTION_IDS,
    )
    def test_true_probe_renders_the_option(self, probe_name, kwargs, fragment, feature):
        """The reference switchboard renders every option it declares."""
        sql = IdentityClause(DummyDialect(), **kwargs).to_sql()[0]
        assert fragment in sql, f"expected {fragment!r} in {sql!r}"

    @pytest.mark.parametrize(
        "probe_name,kwargs,fragment,feature",
        IDENTITY_OPTION_CASES,
        ids=IDENTITY_OPTION_IDS,
    )
    def test_gate_is_per_option(self, probe_name, kwargs, fragment, feature):
        """Withdrawing one probe must not disable the other options.

        This is the difference between a per-option gate and a blanket switch
        that would make the per-option probes decorative.
        """
        dialect = _withdrawing_dialect(probe_name)()
        for other_probe, other_kwargs, other_fragment, _ in IDENTITY_OPTION_CASES:
            if other_probe == probe_name:
                continue
            sql = IdentityClause(dialect, **other_kwargs).to_sql()[0]
            assert other_fragment in sql, (
                f"withdrawing {probe_name} also disabled {other_probe}: "
                f"{other_fragment!r} missing from {sql!r}"
            )

    def test_always_refused_when_generation_always_withdrawn(self):
        """``ALWAYS`` is refused by name, not downgraded to ``BY DEFAULT``."""
        dialect = _withdrawing_dialect("supports_identity_generation_always")()
        with pytest.raises(UnsupportedFeatureError, match="IDENTITY GENERATED ALWAYS"):
            IdentityClause(dialect, "ALWAYS").to_sql()

    def test_by_default_still_renders_when_always_withdrawn(self):
        """The generation gate is for ``ALWAYS``; ``BY DEFAULT`` is untouched."""
        dialect = _withdrawing_dialect("supports_identity_generation_always")()
        sql = IdentityClause(dialect, "BY DEFAULT").to_sql()[0]
        assert sql == " GENERATED BY DEFAULT AS IDENTITY"

    def test_always_renders_where_declared(self):
        sql = IdentityClause(DummyDialect(), "ALWAYS").to_sql()[0]
        assert sql == " GENERATED ALWAYS AS IDENTITY"


class TestMechanismGates:
    """The master switches fail closed before any option is considered."""

    def test_identity_refused_when_mechanism_false(self):
        dialect = _withdrawing_dialect("supports_identity_column")()
        with pytest.raises(UnsupportedFeatureError, match="IDENTITY column"):
            IdentityClause(dialect).to_sql()
        # Options must not sneak past the master switch either.
        with pytest.raises(UnsupportedFeatureError, match="IDENTITY column"):
            IdentityClause(
                dialect, "ALWAYS", start=1, increment=1, minvalue=1, maxvalue=9, cycle=True
            ).to_sql()

    def test_auto_increment_refused_when_mechanism_false(self):
        dialect = _withdrawing_dialect("supports_auto_increment_column")()
        with pytest.raises(UnsupportedFeatureError, match="AUTO_INCREMENT column"):
            AutoIncrementClause(dialect).to_sql()

    def test_sqlite_declines_both_mechanisms(self):
        """SQLite has neither grammar, so both nodes fail closed there."""
        sqlite = SQLiteDialect()
        assert sqlite.supports_identity_column() is False
        assert sqlite.supports_auto_increment_column() is False
        with pytest.raises(UnsupportedFeatureError, match="IDENTITY column"):
            IdentityClause(sqlite).to_sql()
        with pytest.raises(UnsupportedFeatureError, match="AUTO_INCREMENT column"):
            AutoIncrementClause(sqlite).to_sql()


class TestConformanceIsNotVacuous:
    """Guards so the checks above cannot be true by accident."""

    def test_formatter_names_match_the_expressions(self):
        """The names checked are the names the expressions actually dispatch to."""
        assert IdentityClause.format_method.fget(None) == "format_identity_clause"
        assert AutoIncrementClause.format_method.fget(None) == "format_auto_increment_clause"
        for name in ("format_identity_clause", "format_auto_increment_clause"):
            assert hasattr(DummyDialect, name), name

    def test_both_branches_have_a_subject(self):
        """At least one core dialect declares each mechanism and one declines."""
        identity_declaring = [
            c.__name__ for c in CORE_DIALECTS if c().supports_identity_column() is True
        ]
        identity_declining = [
            c.__name__ for c in CORE_DIALECTS if c().supports_identity_column() is False
        ]
        auto_declaring = [
            c.__name__
            for c in CORE_DIALECTS
            if c().supports_auto_increment_column() is True
        ]
        auto_declining = [
            c.__name__
            for c in CORE_DIALECTS
            if c().supports_auto_increment_column() is False
        ]
        assert identity_declaring and identity_declining
        assert auto_declaring and auto_declining

    def test_every_option_case_is_gated_by_a_real_probe(self):
        """Each case names a probe the reference dialect answers ``True``."""
        for probe_name, _, _, _ in IDENTITY_OPTION_CASES:
            assert getattr(DummyDialect(), probe_name)() is True, probe_name
